version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: docker-mariadb
    ports:
      - "5002:3306"
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - maria-data:/data/db
      - ./init.sql:/data/application/init.sql

volumes:
  maria-data:
    driver: local
